app.client - ERROR - Ошибка валидации данных: [{"type":"missing","loc":["data","candles",0,"date"],"msg":"Field required","input":{"timestamp":"2024-03-04T12:23:00Z","open":{"num":16139,"scale":2},"close":{"num":16139,"scale":2},"high":{"num":16139,"scale":2},"low":{"num":16138,"scale":2},"volume":9310},"url":"https://errors.pydantic.dev/2.6/v/missing"}]
app.client - ERROR - Неожиданная ошибка: 1 validation error for CandlesResponse
data.candles.0.date
  Field required [type=missing, input_value={'timestamp': '2024-03-04...le': 2}, 'volume': 9310}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
app.client - ERROR - Ошибка валидации данных: [{"type":"missing","loc":["data","candles",0,"timestamp"],"msg":"Field required","input":{"date":"2024-03-11","open":{"num":16104,"scale":2},"close":{"num":16056,"scale":2},"high":{"num":16128,"scale":2},"low":{"num":16051,"scale":2},"volume":15883610},"url":"https://errors.pydantic.dev/2.6/v/missing"}]
app.client - ERROR - Неожиданная ошибка: 1 validation error for CandlesResponse
data.candles.0.timestamp
  Field required [type=missing, input_value={'date': '2024-03-11', 'o... 2}, 'volume': 15883610}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
app.client - ERROR - Ошибка валидации данных: [{"type":"missing","loc":["data","candles",0,"date"],"msg":"Field required","input":{"timestamp":"2024-03-04T12:23:00Z","open":{"num":16139,"scale":2},"close":{"num":16139,"scale":2},"high":{"num":16139,"scale":2},"low":{"num":16138,"scale":2},"volume":9310},"url":"https://errors.pydantic.dev/2.6/v/missing"}]
app.client - ERROR - Неожиданная ошибка: 1 validation error for CandlesResponse
data.candles.0.date
  Field required [type=missing, input_value={'timestamp': '2024-03-04...le': 2}, 'volume': 9310}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
app.client - ERROR - Ошибка валидации данных: [{"type":"missing","loc":["clientId"],"msg":"Field required","input":{"error":{"code":"NOT_FOUND","message":"The requested resource was not found","data":null}},"url":"https://errors.pydantic.dev/2.6/v/missing"},{"type":"missing","loc":["transactionId"],"msg":"Field required","input":{"error":{"code":"NOT_FOUND","message":"The requested resource was not found","data":null}},"url":"https://errors.pydantic.dev/2.6/v/missing"},{"type":"missing","loc":["securityCode"],"msg":"Field required","input":{"error":{"code":"NOT_FOUND","message":"The requested resource was not found","data":null}},"url":"https://errors.pydantic.dev/2.6/v/missing"},{"type":"string_type","loc":["error"],"msg":"Input should be a valid string","input":{"code":"NOT_FOUND","message":"The requested resource was not found","data":null},"url":"https://errors.pydantic.dev/2.6/v/string_type"}]
app.client - ERROR - Неожиданная ошибка: 4 validation errors for OrderPlacementResponse
clientId
  Field required [type=missing, input_value={'error': {'code': 'NOT_F...t found', 'data': None}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
transactionId
  Field required [type=missing, input_value={'error': {'code': 'NOT_F...t found', 'data': None}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
securityCode
  Field required [type=missing, input_value={'error': {'code': 'NOT_F...t found', 'data': None}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
error
  Input should be a valid string [type=string_type, input_value={'code': 'NOT_FOUND', 'me...ot found', 'data': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
app.client - ERROR - Ошибка валидации данных: [
  {
    "loc": [
      "clientId"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  },
  {
    "loc": [
      "transactionId"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  },
  {
    "loc": [
      "securityCode"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  },
  {
    "loc": [
      "error"
    ],
    "msg": "str type expected",
    "type": "type_error.str"
  }
]
app.client - ERROR - Неожиданная ошибка: 4 validation errors for OrderPlacementResponse
clientId
  field required (type=value_error.missing)
transactionId
  field required (type=value_error.missing)
securityCode
  field required (type=value_error.missing)
error
  str type expected (type=type_error.str)
app.client - ERROR - Ошибка валидации данных: [
  {
    "loc": [
      "clientId"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  },
  {
    "loc": [
      "transactionId"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  },
  {
    "loc": [
      "securityCode"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  },
  {
    "loc": [
      "error"
    ],
    "msg": "str type expected",
    "type": "type_error.str"
  }
]
app.client - ERROR - Неожиданная ошибка: 4 validation errors for OrderPlacementResponse
clientId
  field required (type=value_error.missing)
transactionId
  field required (type=value_error.missing)
securityCode
  field required (type=value_error.missing)
error
  str type expected (type=type_error.str)
app.client - ERROR - Ошибка валидации данных: [
  {
    "loc": [
      "clientId"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  },
  {
    "loc": [
      "transactionId"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  },
  {
    "loc": [
      "securityCode"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  }
]
app.client - ERROR - Неожиданная ошибка: 3 validation errors for OrderPlacementResponse
clientId
  field required (type=value_error.missing)
transactionId
  field required (type=value_error.missing)
securityCode
  field required (type=value_error.missing)
app.client - ERROR - Ошибка валидации данных: [
  {
    "loc": [
      "clientId"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  },
  {
    "loc": [
      "transactionId"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  },
  {
    "loc": [
      "securityCode"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  },
  {
    "loc": [
      "error"
    ],
    "msg": "str type expected",
    "type": "type_error.str"
  }
]
app.client - ERROR - Неожиданная ошибка: 4 validation errors for OrderPlacementResponse
clientId
  field required (type=value_error.missing)
transactionId
  field required (type=value_error.missing)
securityCode
  field required (type=value_error.missing)
error
  str type expected (type=type_error.str)
app.client - ERROR - Ошибка валидации данных: [
  {
    "loc": [
      "clientId"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  },
  {
    "loc": [
      "transactionId"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  },
  {
    "loc": [
      "securityCode"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  }
]
app.client - ERROR - Неожиданная ошибка: 3 validation errors for OrderPlacementResponse
clientId
  field required (type=value_error.missing)
transactionId
  field required (type=value_error.missing)
securityCode
  field required (type=value_error.missing)
app.client - ERROR - Ошибка валидации данных: [
  {
    "loc": [
      "clientId"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  },
  {
    "loc": [
      "transactionId"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  },
  {
    "loc": [
      "securityCode"
    ],
    "msg": "field required",
    "type": "value_error.missing"
  }
]
app.client - ERROR - Неожиданная ошибка: 3 validation errors for OrderPlacementResponse
clientId
  field required (type=value_error.missing)
transactionId
  field required (type=value_error.missing)
securityCode
  field required (type=value_error.missing)
app.client - ERROR - Неожиданная ошибка: 3 validation errors for OrderPlacementResponse
clientId
  field required (type=value_error.missing)
transactionId
  field required (type=value_error.missing)
securityCode
  field required (type=value_error.missing)
app.client - ERROR - Ошибка при размещении ордера: {"data":null,"error":{"code":"UNAVAILABLE","message":"Service temporary unavailable","data":null}}
app.client - ERROR - Неожиданная ошибка: Ошибка при размещении ордера: {"data":null,"error":{"code":"UNAVAILABLE","message":"Service temporary unavailable","data":null}}
app.client - ERROR - Ошибка при получении списка ордеров: {"data":null,"error":{"code":"UNAVAILABLE","message":"Service temporary unavailable","data":null}}
app.client - ERROR - Неожиданная ошибка: Ошибка при получении списка ордеров: {"data":null,"error":{"code":"UNAVAILABLE","message":"Service temporary unavailable","data":null}}
app.client - ERROR - Ошибка при размещении ордера: {"data":null,"error":{"code":"UNAVAILABLE","message":"Service temporary unavailable","data":null}}
app.client - ERROR - Неожиданная ошибка: Ошибка при размещении ордера: {"data":null,"error":{"code":"UNAVAILABLE","message":"Service temporary unavailable","data":null}}
app.client - ERROR - Ошибка при получении списка ордеров: {"data":null,"error":{"code":"UNAVAILABLE","message":"Service temporary unavailable","data":null}}
app.client - ERROR - Неожиданная ошибка: Ошибка при получении списка ордеров: {"data":null,"error":{"code":"UNAVAILABLE","message":"Service temporary unavailable","data":null}}
app.client - ERROR - Ошибка при размещении ордера: {"data":null,"error":{"code":"UNAVAILABLE","message":"Service temporary unavailable","data":null}}
app.client - ERROR - Неожиданная ошибка: Ошибка при размещении ордера: {"data":null,"error":{"code":"UNAVAILABLE","message":"Service temporary unavailable","data":null}}
app.client - ERROR - Неожиданная ошибка: 10 validation errors for GetOrdersResultWebResponse
data -> orders -> 0 -> status
  value is not a valid integer (type=type_error.integer)
data -> orders -> 0 -> buySell
  value is not a valid integer (type=type_error.integer)
data -> orders -> 0 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 0 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 0 -> market
  value is not a valid integer (type=type_error.integer)
data -> orders -> 1 -> status
  value is not a valid integer (type=type_error.integer)
data -> orders -> 1 -> buySell
  value is not a valid integer (type=type_error.integer)
data -> orders -> 1 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 1 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 1 -> market
  value is not a valid integer (type=type_error.integer)
app.client - ERROR - Неожиданная ошибка: 6 validation errors for GetOrdersResultWebResponse
data -> orders -> 0 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 0 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 1 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 1 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 2 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 2 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
app.client - ERROR - Неожиданная ошибка: 8 validation errors for GetOrdersResultWebResponse
data -> orders -> 0 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 0 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 1 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 1 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 2 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 2 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 3 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 3 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
app.client - ERROR - Неожиданная ошибка: type object 'OrderCondition' has no attribute '__args__'
app.client - ERROR - Неожиданная ошибка: 11 validation errors for GetOrdersResultWebResponse
data -> orders -> 0 -> createdAt
  none is not an allowed value (type=type_error.none.not_allowed)
data -> orders -> 1 -> createdAt
  none is not an allowed value (type=type_error.none.not_allowed)
data -> orders -> 2 -> createdAt
  none is not an allowed value (type=type_error.none.not_allowed)
data -> orders -> 3 -> createdAt
  none is not an allowed value (type=type_error.none.not_allowed)
data -> orders -> 4 -> createdAt
  none is not an allowed value (type=type_error.none.not_allowed)
data -> orders -> 5 -> createdAt
  none is not an allowed value (type=type_error.none.not_allowed)
data -> orders -> 6 -> createdAt
  none is not an allowed value (type=type_error.none.not_allowed)
data -> orders -> 7 -> createdAt
  none is not an allowed value (type=type_error.none.not_allowed)
data -> orders -> 8 -> createdAt
  none is not an allowed value (type=type_error.none.not_allowed)
data -> orders -> 9 -> createdAt
  none is not an allowed value (type=type_error.none.not_allowed)
data -> orders -> 10 -> createdAt
  none is not an allowed value (type=type_error.none.not_allowed)
app.client - ERROR - Неожиданная ошибка: type object 'OrderCondition' has no attribute '__args__'
app.client - ERROR - Неожиданная ошибка: 26 validation errors for GetOrdersResultWebResponse
data -> orders -> 0 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 0 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 1 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 1 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 2 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 2 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 3 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 3 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 4 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 4 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 5 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 5 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 6 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 6 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 7 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 7 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 8 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 8 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 9 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 9 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 10 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 10 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 11 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 11 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 12 -> condition -> type
  value is not a valid integer (type=type_error.integer)
data -> orders -> 12 -> validBefore -> type
  value is not a valid integer (type=type_error.integer)
